version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: stg_customers
      - name: stg_employees
      - name: stg_orders
      - name: stg_order_lines
      - name: stg_products
      - name: stg_suppliers
      - name: stg_inventory
      - name: stg_returns
