bi_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('DB_USER', 'biuser') }}"
      password: "{{ env_var('DB_PASSWORD', 'bipass') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME', 'bi_platform') }}"
      schema: staging
      threads: 4
